### ISSUE TITLE
Various places rely on the natur of \space

### ISSUE THREAD

**Issue by josephwright** [latex3/graphics-def#11]
This came up with the example
```latex
\documentclass{article}
\usepackage{listings}
\usepackage{graphicx}
\newcommand{\foobar}[1]{\scalebox{-1}[1]{#1}}
\lstset{breaklines=true,prebreak=\foobar{A}}
\begin{document}
\begin{lstlisting}
some very very very very very very very very very very very very very very very very very very very long line
\end{lstlisting}
\end{document}
```
which gives a fatal error at present as `\space` is expanding to `\kern \lst@width`. Older versions of `pdftex.def` used `\ltx@space` (from HOs stack) to avoid this. However, that wasn't universal so depending on the driver chosen the above would still fail.

Arguably no-one should be messing with `\space` (oh for `\c_space_tl`), but we may have to globally sort this. Perhaps something in the kernel in addition to in the drivers?

**Comment by FrankMittelbach** [comment]
Am 20.06.17 um 17:22 schrieb Joseph Wright:
> Arguably no-one should be messing with |\space| (oh for |\c_space_tl|), 
> but we may have to globally sort this. Perhaps something in the kernel 
> in addition to in the drivers?

I agree, nobody should mess with |\c_space_tl| but |\space| is not the 
same. It is in effect a user level command and as such representing 
whatever in that situation represents a space. So I find it 
understandable that something like |lstlisting| does change it.

So perhaps a real space constant would be in order for the kernel (as 
well as changing the kernel use of |\space| in various places to that 
constant.

**Comment by josephwright** [comment]
It's probably worth noting that this only comes up in the example has the `\space` we need is for writing a special _and_ `listings` has activated it's redefinition locally. I'm not sure there are many other places you'd run into this, at least as long as `\space` is only set locally (which is likely why it's not come up more widely). I guess Heiko might have seen it before, hence originally using `\ltx@space` ...
