### ISSUE TITLE
multidot regression with xelatex

### ISSUE THREAD

**Issue by kberry** [latex3/graphics-def#12]
trivial document (any image with multidot name) works with xelatex in tl16 and tl17 as originally distributed (<use  "x.1.png" >), but fails with xelatex in current tl. presumably due to graphics changes. this seems unfortunate.
```latex
\documentclass{article}
\usepackage{graphicx}
\begin{document}
\includegraphics{x.1.png}
\end{document}
```
fyi, it fails in all cases with lualatex, but that's ok. of course it would be nice if it "just worked" with both engines.

`[multidot]{grffile}` also fails with current tl; reporting that separately in `oberdiek`.

(originally reported by leo liu on tex-live list, but never got resolved there.)

**Comment by davidcarlisle** [comment]
The documented behaviour of the graphics package has always been that that
would be handled as unknown extension 1.png so probably not work, it may be
that the default filetype for xetex has effectively changed for xetex from
bitmap to eps, I'll need to test with the older release, however a more
standard markup would be

\documentclass{article}
\usepackage{graphicx}

\def\dt{.}

\begin{document}
\includegraphics{x\dt 1.png}
\end{document}

which works with pdftex, xetex and luatex.

The reasons for not handling multiple extensions don't really apply now as
they were mostly concerns with (not) building some pipeline of
decompression commands for foo.eps.gz or foo.eps.Z or whatever, and keeping
the graphics handling within the memory constraints of emtex....

But if we change that we should change filename@parse (in the latex format)
not in individual .def files.

David

**Comment by josephwright** [comment]
@davidcarlisle   I'd favour fixing this in the kernel (and updating `grffile` so it knows about that) (could be done first in the drivers if we want to hold off on a full release). Are you OK with that? Basically we'd take the extension lookup code from `grffile` and add to `\filename@parse`.

**Comment by davidcarlisle** [comment]
note that there are separate issues somewhat combined in the test file,

what do do with unknown extensions. latex+dvips classically treated them as
eps so the bounding box reading code would work at least on a .bb file, and
tex only needed the size anyway, pdftex tried reading the file natively as
it was worth a try....  this is (I think) what's changed here as xetex is
now treating .foo as eps in the size determination  (which possibly isn't
the best default) the fact that .foo is .1.png  here is secondary.

what to do with multiple dots. If  x.1.png was changed to be parsed as x.1
+ .png with extension .png then it would work in this case however doing
this fully in the kernel might be problematic, if you want
`\includegraphics{x.1}` to work it's not enough to just parse to the last
dot you need to add extensions to the end after checking if files exist
which means that it's no longer just a string parser it's environment
dependent and potentially depends on encoding support for filenames.
grffile handles this well enough but as a package, it can assume inputenc
(and other things) are available.  It may work out well enough to change
the format to take the last dot in filename@parse and leave any filesystem
lookup to graphics package but the exact boundaries would need a bit of
documentation.

whatever we do we should check that it remains the case that you can use
the keyval arguments to \includegraphics to disable filename parsing and
supply basename and extension explicitly .

**Comment by josephwright** [comment]
@davidcarlisle  OK, in that case I'll look to fix at the `grffile` end.

**Comment by kberry** [comment]
the reason the test file contains both issues is because both are needed to exhibit the problem, as far as i could see.

i am aware of historical behavior, documentation, etc. the point is the reversion in xelatex behavior (yes, the difference is that it is now being treated as eps). seems either the reversion should be fixed or explicitly acknowledged. i'm still not clear which way you're planning to go.

i'm certainly in favor of taking the last dot as defining the extension instead of the first. seems to me that would fix 99% of cases without users needing to bother with grffile.

in principle, for users .1.png is surely not an "unknown extension", it is perfectly clear (to them) that a .png file is intended.

thanks.

**Comment by davidcarlisle** [comment]
On 21 July 2017 at 23:47, kberry <notifications@github.com> wrote:

> the reason the test file contains both issues is because both are needed
> to exhibit the problem, as far as i could see.
>
> i am aware of historical behavior, documentation, etc. the point is the
> reversion in xelatex behavior (yes, the difference is that it is now being
> treated as eps). seems either the reversion should be fixed or explicitly
> acknowledged. i'm still not clear which way you're planning to go.
>
> i'm certainly in favor of taking the last dot as defining the extension
> instead of the first. seems to me that would fix 99% of cases without users
> needing to bother with grffile.
>
> in principle, for users .1.png is surely not an "unknown extension", it is
> perfectly clear (to them) that a .png file is intended.
>

yes sure that's why I've just been musing about possibilities rather than
just reverting the previous behaviour of making xetex.def  default to
bitmap so that .1.png sort of worked via a fallback case.

changing filename@parse to split on the last dot rather than the first
would fix this case but it isn't clearly the right thing to do just that,
as for example it would require some fairly extensive changes to the logic
in graphics.sty that sets up .eps.gz (which isn't as important as it was
but I don't want to break it)

I suspect some version that takes the last dot but special cases .gz so
foo.xxx.gz gets split as foo + xxx.gz probably would work best but I'm
going to leave it till next week and not code anything straight away
(you're not the only one that isn't clear what we're planning to do :-)

> thanks.
>
>

**Comment by davidcarlisle** [comment]
With the current multi-dot code in the format and graphics.sty the example in the original report seems to work in xetex, luatex and pdftex, so we can close, I think.

**Comment by PhelypeOleinik** [comment]
Closing as fixed
