### ISSUE TITLE
pdftex-def ignores bb option

### ISSUE THREAD

**Issue by persiobarros** [latex3/graphics-def#14]
Latest version of pdftex-def (1.0g) does not handle bb (bounding box) option from graphicx package. Previous versions deferred it to viewport option (with a warning). With this new behavior, if a bb option is found, the graphic file is not included in the precessed document, leaving a blank box instead, with no error message. The trouble is that LyX generates bb option in some situations.
Is that the intended behavior?

**Comment by josephwright** [comment]
I guess I'll have to fix this: I personally don't like the idea of changing the `bb` (preferring to view it as fixed and adjust the `viewport`), but it is long-standing. I'll see if I can sort it this week.

**Comment by josephwright** [comment]
Fixed by https://github.com/latex3/graphics-def/commit/9e6d682fe28c3811410e0faae70c75e586fc8b05
