### ISSUE TITLE
fi ligature not in text output from xelatex 2018

### ISSUE THREAD

**Issue by kberry** [latex3/graphics-def#17]
original report from ulrike:
http://tug.org/pipermail/tex-live/2018-May/041608.html

it's not clear to me if this is a fontspec issue, a driver issue, a xetex  issue, or something else. posting here is just a guess, since i think you guys are much more likely to actually investigate enough to find the culprit than anyone else (e.g., me or jonathan :).

i tried running ulrike's test file (attached) with both luatex and xetex, both tl2017 and current tl-dev. only xelatex-2018 fails. i used pdftotext unilig.pdf - as a quick way to discern whether the ligature was in the output text (as letters "f" and "i"). lots of changes to almost all files, as one would expect.

[unilig.zip](https://github.com/latex3/graphics-def/files/1977161/unilig.zip)

**Comment by u-fischer** [comment]
Imho it is an engine problem (either xetex or xdvipdfmx) as these plain tex example show the same problem:

```
\font\test="[FrutigerLTCom-Light.ttf]/OT:script=latn;language=DFLT;mapping=tex-text;"
\test Prefix

\bye

\font\test="[Roboto-Regular.ttf]/OT:script=latn;language=DFLT;mapping=tex-text;"
\test Prefix

\bye
```

**Comment by kberry** [comment]
thanks ulrike. i did not know the plain tex test was so straightforward. closing here.
