### ISSUE TITLE
pdflatex: arithmetic: number too big with certain .png

### ISSUE THREAD

**Issue by kberry** [latex3/graphics-def#18]
reported by Ilya Zakharevich <nospam-abuse@ilyaz.org> at https://tug.org/pipermail/tex-live/2018-June/041951.html. Attached png running through pdflatex (or xelatex or lualatex) gets 

pdfTeX warning: pdflatex: arithmetic: number too big

and a "weird" pdf output page. he says it worked fine for him in 2009, but I don't get a difference with anything from 2009--current development.

what seemed odd to me is that when i run it through plain pdftex, with

\pdfximage width1.5in{x.png}\pdfrefximage\pdflastximage\end

it worked fine. output is as expected, no arithmetic warnings. this made me think that maybe something in the latex drivers could potentially address it. or maybe there is nothing to be done. i don't know, but i'm hoping you'll take a look.

[plainpng.pdf](https://github.com/latex3/graphics-def/files/2131083/plainpng.pdf)

**Comment by kberry** [comment]
darn it, forgot other attachments.
![x](https://user-images.githubusercontent.com/362855/41822237-91555228-77a1-11e8-9252-ea4301a19d38.png)

[try2018.txt](https://github.com/latex3/graphics-def/files/2131085/try2018.txt)

p.s. it is pretty annoying that github won't let me upload a .tex file. any way to allow that?

**Comment by davidcarlisle** [comment]
the restriction on file extensions is site wide so nothing can be done
other than ask github, however changing the extension or just posting the
code inline works Ok in most case.  I'll look at the example...

**Comment by kberry** [comment]
Akira wrote me, FYI:
------
I confirmed that
\pdfximage height 3cm {try-tl2018a.png}
\pdfrefximage\pdflastximage
\bye
works normally. Does pdftex use C function to calculate the size of images?

extractbb shows
%%BoundingBox: 0 0 73555 13810
73555bp = 4838577357sp > 2^30sp
So calculation may be impossible as a TeX number.
------

**Comment by u-fischer** [comment]
Loading the image at the "natural" size in plain gives the same warning:

~~~~
\pdfximage {try-tl2018a.png}%
\pdfrefximage\pdflastximage
\bye
~~~~

~~~~
pdfTeX warning: pdftex.exe: arithmetic: number too big

Overfull \vbox (13098.09746pt too high) has occurred while \output is active
\vbox(643.20255+0.0)x469.75499
.\pdfrefximage(13731.3+0.0)x--32768.0
.\glue(\topskip) 10.0
.\hbox(0.0+0.0)x469.75499
.\glue 0.0 plus 1.0fill
~~~~

As latex has to load it this way to get the natural size I don't see how it could avoid the warning. The image is simply too large. @davidcarlisle  Should we close this?

**Comment by kberry** [comment]
if you're up for it, you could write the original poster (at the top here) and see if it really worked for him in an older version. i suppose pdftex is (internally) computing the scaled versions with more bits available.

**Comment by davidcarlisle** [comment]
I think I'll close this here, it's a pdftex not macro issue, and already quite old.

**Comment by ArneBab** [comment]
This can happen when you try to embed a jpg with setting 1dpi. Converting to png without dpi info helped.
