### ISSUE TITLE
dvisvgm.def: cancels EPS support

### ISSUE THREAD

**Issue by agrahn** [latex3/graphics-def#19]
The file `dvisvgm.def` cancels `dvisvgm`'s built-in support for EPS (via the `PSFILE` `\special` and libgs from Ghostscript):

```latex
\documentclass[dvisvgm]{article}
\usepackage{graphicx}

\begin{document}
\includegraphics{example-image.eps}% ! LaTeX Error: Unknown graphics extension: .eps.
\end{document}
```

EPS support can be re-instated by using the corresponding lines from `dvips.def`. Could these be added to `dvisvgm.def`?

```latex
\documentclass[dvisvgm]{article}
\usepackage{graphicx}

\makeatletter
\edef\Gin@extensions{.eps,.ps,mps,\Gin@extensions}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%copied from graphics-def/dvips.def for EPS inclusion
\def\Ginclude@eps#1{%
  \message{<#1>}%
  \bgroup
  \def\@tempa{!}%
  \dimen@\Gin@req@width
  \dimen@ii.1bp%
  \divide\dimen@\dimen@ii
  \@tempdima\Gin@req@height
  \divide\@tempdima\dimen@ii
    \special{PSfile="#1"\GPT@space
      llx=\Gin@llx\GPT@space
      lly=\Gin@lly\GPT@space
      urx=\Gin@urx\GPT@space
      ury=\Gin@ury\GPT@space
      \ifx\Gin@scalex\@tempa\else rwi=\number\dimen@\GPT@space\fi
      \ifx\Gin@scaley\@tempa\else rhi=\number\@tempdima\GPT@space\fi
      \ifGin@clip clip\fi}%
  \egroup}

\@namedef{Gin@rule@.ps}#1{{eps}{.ps}{#1}}
\@namedef{Gin@rule@.eps}#1{{eps}{.eps}{#1}}
\@namedef{Gin@rule@.mps}#1{{eps}{.mps}{#1}}
\@namedef{Gin@rule@*}#1{{eps}{\Gin@ext}{#1}}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\makeatother

\begin{document}
  \includegraphics[width=0.5\linewidth]{example-image.eps}
\end{document}
```

**Comment by davidcarlisle** [comment]
Looks like we should do that, thanks for the comment,

perhaps not

\@namedef{Gin@rule@*}#1{{eps}{\Gin@ext}{#1}}


though?

Even for dvips I'm wondering if defaulting to EPS makes as much sense in
2018 as it did in 1994.

without that you get a more or less understandable "unknown extension"
error if you try a .pdf or .gif or something
but with it you get a rather more confusing "can't read bounding box" error
as it tries to find a postscript BoundingBox comment in some arbitrary file
type.

At the time EPS was quite likely (and I needed to support MetaPost's output
with names .1, .2, ....  but now things are more complicated:-)

**Comment by agrahn** [comment]
On Fri, Nov 02, 2018 at 06:32:08AM -0700, David Carlisle wrote:
>Looks like we should do that, thanks for the comment,
>
>perhaps not
>
>\@namedef{Gin@rule@*}#1{{eps}{\Gin@ext}{#1}}

Yes, omit that line. I did not look at this one too close and I wasn't
aware of its implications.

As for the extensions list, I would prefer the Postscript ones to show up
in front of the bitmapped formats (PNG, JPEG) because of the higher quality of
a vector format.

Thank you.

**Comment by davidcarlisle** [comment]
@agrahn  Hopefully that covers it, I'll push to ctan in a day or so unless something shows up.
