### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by vladikKreinovich** [latex3/graphics-def#21]
I recently had MikTeX reinstalled since I was switched to Windows10, now some of my LaTeX files that previously worked stopped working, I get an error message

"Package pdftex.def Error: File `but.pdf' not found"

I tried to google this error, could not find it. None of the files that I designed start with but. Please help

**Comment by davidcarlisle** [comment]
Note this is a bug report tracker not a help forum (tex.stackexchange.com would be more suitable) but that means you have `\includegraphics{but.pdf}` but that file can not be found.

**Comment by vladikKreinovich** [comment]
I understand that, the problem is that I am using slide files that follow a pattern including the statement  \paneloverlay{but.pdf} This file is supposed to be provided by the package graphics-def which is part of MikTeX.


In the past, this all worked, but now when I reinstalled MikTeX and WinEdt, for some reason, the system cannot find its own file but.pdf


I can probably find it and add it again, but the file should be already there, this part of the MikTeX installation.


To me, if something worked OK and stopped working in a new version without any warning, it is a bug.


Here is a standard beginning that I copies for all previous files that worked OK:


\documentclass[a4paper]{article}
\usepackage[latin1]{inputenc}
\usepackage{xspace,colortbl}
\usepackage[screen,panelright,code,sectionbreak,paneltoc,chocolate]{pdfscreen}
\usepackage{pause}
\begin{screen}
 \margins{.35in}{.45in}{.35in}{.35in}
 \screensize{5.25in}{7in}
 \paneloverlay{but.pdf}
 \def\pfill{\vskip6pt}
 \definecolor{panelbackground}{rgb}{0.5,0.5,0.9}
 \backgroundcolor{white}
 \paneloverlayempty
\end{screen}
\pagedissolve{Wipe /D 0 /Dm /V /M /O}
\setlength{\parindent}{0cm}
\begin{document}

?


________________________________

**Comment by blefloch** [comment]
FWIW, I find the following in TeXLive 2018.  Haven't checked TeXLive 2019.

/usr/local/texlive/2018/texmf-dist/tex/latex/pdfscreen/but.pdf

**Comment by FrankMittelbach** [comment]
> To me, if something worked OK and stopped working in a new version without any warning, it is a bug.

true, but then you need to report the problem to maintainer of the software. TeX/LaTeX is a huge universe and the LaTeX Project only maintains the core LaTeX format and and core packages but not the distributions, the engines, the editors the contributed packages etc. Granted it is not always easy to understand whom to address, but we aren't the right people as we can neither fix pdfscreen or change miktex etc. 

By the way, on the Mac here with TL 2019 your sample find bug.pdf, so perhaps it is an issue with MikTeX, which we can't help with , sorry.

This is why we on the bugtracker for latex2e ask to always produce a running example  that shows the problem and that starts with
```
\RequirePackage{latexbug}
```
on the first line.

This would then have clearly indicated that your issue needs to be handled elsewhere.

Obviously for this sub-repository this guidence hasn't been set up (which should happen)

**Comment by u-fischer** [comment]
but.pdf is in my miktex and is found without problems. If you still have problems you should ask with a complete example e.g. a tex.stackexchange or in the miktex issue tracker.
