### ISSUE TITLE
graphicx and eplain

### ISSUE THREAD

**Issue by GHT54** [latex3/graphics-def#34]
!! Please fill out all sections after reading CONTRIBUTING guidelines (and remove lines starting with !!)

## Brief outline of the bug
New versions of pdftex.def and dvips.def produce errors with eplain and graphicx 

## Minimal example showing the bug

Plain TeX documenr

\input eplain
\input graphicx
test
\end
```


## Log file (required) and possibly PDF file  

!! Use drag-and-drop  (remember: .log file is required) !!

[essai.log](https://github.com/latex3/graphics-def/files/9648167/essai.log)

**Comment by davidcarlisle** [comment]
thanks, we will fix, but meanwhile you can do

```
\input eplain
\expandafter\def\expandafter\newdimen\expandafter{\newdimen}
\input graphicx
test
\end
```

**Comment by GHT54** [comment]
Many thanks indeed.
Regards,

Gérald

David Carlisle a écrit le 26/9/22 à 20:08 :

**Comment by davidcarlisle** [comment]
update of graphics-pln is installed at ctan, will reach distributions in a day or so.
