### ISSUE TITLE
natwidth and natheight

### ISSUE THREAD

**Issue by persiobarros** [latex3/graphics-def#4]
Latest version of pdftex.def (v0.06j) cannot cope with "natwidth" and "natheight" includegraphics options.
The following patch seems to solve this issue:

986a987,988
>     \define@key{Gin}{natwidth}{\GPT@disable{natwidth}}%
>     \define@key{Gin}{natheight}{\GPT@disable{natheight}}%

Thanks,
Persio Barros

**Comment by persiobarros** [comment]
Patch file content follows:

`--- pdftex.def	2016-12-21 11:54:43.847914205 -0200
+++ pdftex-modif.def	2016-12-21 11:59:28.087913084 -0200
@@ -984,6 +984,8 @@
     \define@key{Gin}{bblly}{\GPT@disable{bblly}}%
     \define@key{Gin}{bburx}{\GPT@disable{bburx}}%
     \define@key{Gin}{bbury}{\GPT@disable{bbury}}%
+    \define@key{Gin}{natwidth}{\GPT@disable{natwidth}}%
+    \define@key{Gin}{natheight}{\GPT@disable{natheight}}%
   \fi
 }
 \AtBeginDocument{\GPT@fix}
`

**Comment by davidcarlisle** [comment]
Just to confirm, you are suggesting making these give a warning then do nothing? The older code made them silently do nothing, I don't see any record of intending to drop that section so it may have been in error while refactoring for luatex changes. I'll check.

**Comment by persiobarros** [comment]
Sorry for the lack of information.
The current v0.06j code generates an error on those options. But older versions did drop them silently. So, my suggestion is to just restore the old behavior (with a warning).

**Comment by davidcarlisle** [comment]
After the update for issue https://github.com/latex3/latex2e/issues/21 These keys are no longer silently ignored (they give the same error as the bounding box keys like `bbllx`) so closing here.
