### ISSUE TITLE
\scalebox with positive scale factor

### ISSUE THREAD

**Issue by aminophen** [latex3/graphics-def#6]
A report from Japanese user. When \scalebox is used in math equation, the content is wrongly placed. Here is the MWE and a patch:

~~~~ tex
%#!pdflatex
\documentclass{article}
\usepackage{amsmath}
\usepackage{graphics}

%%% patch begin
\makeatletter
\long\def\newGscale@box#1[#2]#3{%
  \leavevmode
  \def\Gscale@x{#1}\def\Gscale@y{#2}%
  \setbox\z@\hbox{{#3}}%
  \setbox\tw@\hbox{\Gscale@start\rlap{\copy\z@}\Gscale@end}%
  \ifdim#2\p@<\z@
    \ht\tw@-#2\dp\z@
    \dp\tw@-#2\ht\z@
  \else
    \ht\tw@#2\ht\z@
    \dp\tw@#2\dp\z@
  \fi
  \ifdim#1\p@<\z@
    \hb@xt@-#1\wd\z@{\kern-#1\wd\z@\box\tw@\hss}%
  \else
% change from ...
%    \wd\tw@#1\wd\z@
%    \box\tw@
% ... to
    \hb@xt@#1\wd\z@{\box\tw@\kern#1\wd\z@\hss}%
% can fix the issue
  \fi}
\makeatother
%%% patch end

\begin{document}
\def\contents{\scalebox{2}{a}}

$\frac{\contents}{\contents}$
$\frac{\contents}{\contents\kern1sp}$ % wrong!

\makeatletter
\let\Gscale@box\newGscale@box
\makeatother

$\frac{\contents}{\contents}$
$\frac{\contents}{\contents\kern1sp}$ % correct

\end{document}
~~~~

**Comment by davidcarlisle** [comment]
hmm seem like you are right:(

Thanks for that, I'll fix before the next release (in the base latex svn,
not here)

David

**Comment by aminophen** [comment]
> Thanks for that, I'll fix before the next release (in the base latex svn, not here)

Oh, sorry for reporting on wrong repo. Should I re-post this to LaTeX bugs database?

**Comment by davidcarlisle** [comment]
On 31 March 2017 at 13:43, Hironobu Yamashita <notifications@github.com>
wrote:

> Thanks for that, I'll fix before the next release (in the base latex svn,
> not here)
>
> Oh, sorry for reporting on wrong repo. Should I re-post this to LaTeX bugs
> database?
>
>
No, here is fine, I get to be the one to fix it either way:-)

David

**Comment by davidcarlisle** [comment]
updated as suggested in latex svn https://www.latex-project.org//svnroot/latex2e-public/trunk/required/graphics/

**Comment by aminophen** [comment]
Thank you very much!
