### ISSUE TITLE
\includegraphics with \subimport* and luatex.def

### ISSUE THREAD

**Issue by Ri-Ga** [latex3/graphics-def#7]
Using `\includegraphics` to include a PDF from within a `\subimport*`ed file in lualatex failes with a "not found" error for the PDF to be included. The same example compiles as expected when pdflatex is used. A MWE is attached: [MWE.zip](https://github.com/latex3/graphics-def/files/950097/MWE.zip)

I could already trace back the issue to the `\GPT@IfFileExists` macro, which gets passed the "full path" to the PDF as `#1`. By "full path" I refer to the path given to `\includegraphics` prefixed by the `\subimport*` path. The `\IfFileExists` in `\GPT@IfFileExists` then fails to find the file under this path when lualatex (i.e., luatex.def) is used. With pdflatex (pdftex.def), the argument given to `\GPT@IfFileExists` is the same but the macro does not fail (internally it does not use `\IfFileExists`).

As a work-around for the issue, I'm currently just disabling the `\GPT@IfFileExists` check via `\renewcommand\GPT@IfFileExists[1]{\@firstoftwo}`. At least for my code (the issue originally was triggered in a large document) the work-around solves the problem. (I noticed that at least when `\includegraphics` is used the `\GPT@IfFileExists` check is redundant, as `\includegraphics` conducts its own `\IfFileExists` check before `\GPT@IfFileExists` is invoked.)

I could trigger the error with TeXLive 2016 as well as with the most recent graphics.sty and luatex.def. The problem seems to be the successor of [this StackExchange problem](http://tex.stackexchange.com/questions/267572/lualatex-does-not-work-with-import-subimport-when-used-in-standalone-setup), the solution to which worked for me with TeXLive 2015 but no longer works with TeXLive 2016.

**Comment by Ri-Ga** [comment]
I just tried again with the most recent version of graphics-def (from github) and latex-graphics (from CTAN). With the new versions:

- the problem still exists
- my proposed hack/solution does no longer work because the `GPT@IfFileExists` macro no longer exists
- so far, I do not have an updated hack/solution that suits the new versions.

**Comment by davidcarlisle** [comment]
Hmm the analogue of disabling the test in the old code would be to change around line 128 of luatex.def to
```

\def\Gread@pdftex#1{%
%\IfFileExists{#1}
\@firstoftwo

```

and that does in fact make your example work.


the reason that it works  in pdftex is that essentially the same logic is coded with the test

`\expandafter\ifx\expandafter\relax\pdffilesize{#1}\relax`

rather than

`\IfFileExists{#1}`

but `\pdffilesize` is no longer available in luatex.

It's not clear why the import package redefinition are stopping \IfFileExists from seeing sub/square.pdf (or at least I haven't had time to look yet, but I suspect that the import prefix is being added twice at some stage so it's looking for sub/sub/square.pdf) it may be an issue with the import package rather than luatex.def but hopefully the above definition will work for you in the cases the image is known to be there.

Will look later whether it can be made to work by default.

**Comment by davidcarlisle** [comment]
The reason that this fails is that graphics has already done an ` \IfFileExists` in `\Gin@getbase` and so (after `import` has adapted that) the filename that is passed to the driver has already been prefixed with the directory name, as if the input had been

`\includegraphics{sub/picture.pdf}`

The code that checks for the image size historically checks for the file existing again as it was often a different file. `.bmp` for the image and `.bb` to read for a file size, for example.

However the core code uses primitive file checks `  \ifeof\@inputcheck` in `\Gread@eps@aux` in `graphics` and `\pdffilesize` in `pdftex.def` so they work with the `import` modified file path but `luatex.def` uses `\IfFileExists` which means that the file path gets modified again, and works as `\includegraphics{sub/sub/picture.pdf}` which fails.

In practice the "read file" in the pdf case is _always_  the pdf file so it is safe to disable the test completely as suggested in the earlier comments, however in principle someone could use the `read=...` key to `\includegraphics` to change this, so it would be better to keep the file exists test here.

So while arguably this is an issue created by the import package, it's not clear how that package on its own could fix it, and using "relative" filenames is something we might want to address in the  core latex code at some point so we could consider using a test other than `\IfFileExists` here, probably a direct `\ifeof` check as in the eps case (or could consider using a Lua test).

Leaving the issue open for now.

**Comment by davidcarlisle** [comment]
Fixed by the above commit, closing.
